-- pgvectorscale extension
CREATE EXTENSION IF NOT EXISTS vectorscale CASCADE;

-- pgai extension
CREATE EXTENSION IF NOT EXISTS ai CASCADE;

-- Create table for story fragments
CREATE TABLE IF NOT EXISTS story (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fragment TEXT NOT NULL
);

-- Create table for the chat_history
CREATE TABLE IF NOT EXISTS history (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_query TEXT NOT NULL,
    ollama_response TEXT NOT NULL,
    timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Create a vectorizer for the 'story' table
SELECT ai.create_vectorizer(
    'story'::regclass,
    destination => 'story_embeddings',
    embedding => ai.embedding_openai('text-embedding-3-small', 1536),
    chunking => ai.chunking_recursive_character_text_splitter('ollama_response')
);

-- Create a vectorizer for the 'story' table
SELECT ai.create_vectorizer(
    'history'::regclass,
    destination => 'history_embeddings',
    embedding => ai.embedding_openai('text-embedding-3-small', 1536),
    chunking => ai.chunking_recursive_character_text_splitter('fragment')
);

-- Create an index on the story embeddings for faster searches
CREATE INDEX IF NOT EXISTS story_embedding_idx ON story_embeddings_store USING diskann (embedding);

-- Create an index on the history embeddings for faster searches
CREATE INDEX IF NOT EXISTS history_embedding_idx ON history_embeddings_store USING diskann (embedding);

